blank_issues_enabled: false

contact_links:
  - name: Godot documentation repository
    url: https://github.com/godotengine/godot-docs
    about: Please report issues with documentation on the Godot documentation repository, not here.

  - name: Godot community channels
    url: https://godotengine.org/community
    about: Please ask for technical support on one of the other community channels, not here.
