name: ðŸª² Godot CPP
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  # Used for the godot-cpp checkout.
  GODOT_CPP_BRANCH: 4.3

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-cpp-tests
  cancel-in-progress: true

jobs:
  godot-cpp-tests:
    runs-on: ubuntu-24.04
    name: Build and test Godot CPP
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Checkout godot-cpp
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: godotengine/godot-cpp
          ref: ${{ env.GODOT_CPP_BRANCH }}
          path: godot-cpp

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Setup GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Download GDExtension interface and API dump
        uses: ./.github/actions/download-artifact
        with:
          name: godot-api-dump
          path: ./godot-cpp/gdextension

      # TODO: Enable caching when godot-cpp has proper cache limiting.

      # - name: Restore Godot build cache
      #   uses: ./.github/actions/godot-cache-restore
      #   with:
      #     cache-name: godot-cpp
      #   continue-on-error: true

      - name: Build godot-cpp test extension
        env: # Keep synced with godot-build.
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
          SCONS_CACHE_LIMIT: 7168
        run: scons --directory=./godot-cpp/test target=template_debug dev_build=yes verbose=yes

      # - name: Save Godot build cache
      #   uses: ./.github/actions/godot-cache-save
      #   with:
      #     cache-name: godot-cpp
      #   continue-on-error: true
