name: GHA
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-pipeline
  cancel-in-progress: true

jobs:

  static:
    name: 'ğŸ“Š Static'
    uses: ./.github/workflows/static_checks.yml

  android:
    name: 'ğŸ¤– Android'
    uses: ./.github/workflows/android_builds.yml

  ios:
    name: 'ğŸ iOS'
    uses: ./.github/workflows/ios_builds.yml

  linux:
    name: 'ğŸ§ Linux'
    uses: ./.github/workflows/linux_builds.yml

  macos:
    name: 'ğŸ macOS'
    uses: ./.github/workflows/macos_builds.yml

  web:
    name: 'ğŸŒ Web'
    uses: ./.github/workflows/web_builds.yml

  windows:
    name: 'ğŸ Windows'
    uses: ./.github/workflows/windows_builds.yml

  tip:
    if: (github.event_name != 'pull_request') && (github.ref == 'refs/heads/master')
    name: 'ğŸš€ Update tip'
    needs:
      - android
      - ios
      - linux
      - macos
      - web
      - windows
    uses: ./.github/workflows/tip.yml
